baseURL = "http://example.org/"
languageCode = "en-us"
title = "Reaper: Easy Repair Management for Apache Cassandra"
theme = "hugo-universal-theme"

googleAnalytics = ""


[menu]

[[menu.main]]
    name = "Documentation"
    url = "/docs/"

[[menu.main]]
    name = "Downloads"
    url = "/download/"

[[menu.main]]
    name = "FAQ"
    url = "/faq/"

[[menu.main]]
    name = "View on GitHub"
    url = "https://github.com/thelastpickle/cassandra-reaper"


[params]

[params.carousel]
    enable = true
